### PR TITLE
Adds karaoke

### PR DESCRIPTION
**Pull request by simonbs**
This is a rough implementation of recording Animoji karaoke videos. There are still some issues with the implementation. Since my iPhone X is currently being replaced by Apple I'm unable to investigate these issues further until I receive a replacement device.

The feature was put together as part of a hackathon and has its rough edges which is why it is not yet merged into the master branch.

Pessing "Start karaoke" starts a flow for searching and picking a video from YouTube. When a video is picked, it can be played and users can bbe the desired time of the video to start their recording at.

Pressing record will then play the video while recording. When exporting the Animoji video, the audio from the original Animoji video is removed and replaced with the audio from the YouTube video.

screenshot

### CODE REVIEW

**Comment by psppro26** [comment]
Very nice dude !

**Comment by psppro26** [comment]
I installed this on my phone but i see no change and there is no karaoke button ?

**Comment by simonbs** [comment]
@psppro26 Ah, right. You'll need to [follow Googles guide on obtaining a YouTube API key](https://developers.google.com/youtube/v3/getting-started) and set it as the value for SBSYouTubeAPIKey in the Info.plist.

**Comment by psppro26** [comment]
@simonbs just did working great ! good work bro <3

**Comment by psppro26** [comment]
just found some bug : 

- when replay animoji the song its like the animoji is not syncro with the music but when i send it its good ( send it in video )

- the merged.mov (animoji with the song ) is sended only by the first time sharing , if i send and replay again it send a animoji muted

**Comment by psppro26** [comment]
and just asking , dont know if its possible : there is a way to send that karaoke not in video in messages but like in real animoji like apple ? cause its so much smoother , and animoji play without need to launch the video etc

**Comment by soh20** [comment]
Hi @simonbs i tried to add the value for the youtube karaoke but i dont see the button.
i downloaded the version which was recently updated 7 days ago. Or do i have to use a new one?

**Comment by simonbs** [comment]
@soh20 You need to use the [feature/karaoke branch](https://github.com/simonbs/SBSAnimoji/tree/feature/karaoke).

**Comment by soh20** [comment]
Thanks for the fast reply. Now with this version i get this error even though the files are there:

/Users/soh20/Library/Developer/Xcode/DerivedData/SBSAnimoji-crpdlkbafsthiygizkbntydqbiyp/Build/Intermediates.noindex/SBSAnimoji.build/Debug-iphoneos/SBSAnimoji.build/Script-72AD797A1FB4BA7C004D234F.sh: line 2: /usr/local/bin/carthage: No such file or directory

**Comment by simonbs** [comment]
@soh20 Sounds like you didn't install [Carthage](https://github.com/Carthage/Carthage).

**Comment by soh20** [comment]
@simonbs thanks mate. got it running now with the karaoke version and i see the "Start karaoke" button but i cant find any songs in the search bar.

Yes i created a youtube api key and added it in the plist as you wrote above.

**Comment by soh20** [comment]
WORKS now. thanks a lot mate. :)

**Pull request closed without merging**
